version: '3'

services:
  database:
    image: postgres
    env_file:
      - database.env
    volumes: 
      - ./postgres_data:/var/lib/postgresql:rw
    ports:
      - '8001:5432'
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./src/.env
    links:
      - 'database'
      - 'database:db'
