version: '3'

services:
  database:
    image: postgres
    restart: always
    env_file:
      - ./database.env
    volumes: 
      - ./postgres_data:/var/lib/postgresql:rw
    ports:
      - '8001:5432'
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./src/.env
    links:
      - 'database'
      - 'database:db'
    ports:
      - '49666:49666'
